### PR TITLE
Fix asymetric fragmentation buffers

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/19/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/18/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/20/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/19/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/21/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/20/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/22/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/21/)

**Review by jamoralp — APPROVED** [review]
:eyes:

**Pull request merged**
