### PR TITLE
check_configuration.cmake: enable correct language CXX

### PR DESCRIPTION
**Pull request by bkueng**
I got this error in a CI build:
```
CMake Error at cmake/common/check_configuration.cmake:120 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  $<COMPILE_LANGUAGE:...> Unknown language.
```

The same build works locally though.

Other projects are affected by this as well.

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/76/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/71/)

**Comment by pablogs9** [comment]
Which toolchain are you using?

**Comment by bkueng** [comment]
GCC on linux

**Comment by gavanderhoorn** [comment]
This was changed in #67 to fix #57.

Micro-CDR is not a C++ project -- the tests use it though, but the sub-`CMakeLists.txt` configures it.

**Comment by bkueng** [comment]
I only saw it in a CI build, and the same build works locally. I'm not sure where the difference comes from. The change fixes the CI build though, and given the instructions further down `$<$<COMPILE_LANGUAGE:CXX>`, it's clearly incorrect if C++ isn't enabled.

The alternative (and IMO better) way is to remove `$<COMPILE_LANGUAGE:CXX>`. It shouldn't be required, as it's C code.

**Comment by gavanderhoorn** [comment]
> given the instructions further down `$<$<COMPILE_LANGUAGE:CXX>`, it's clearly incorrect if C++ isn't enabled.

`$<COMPILE_LANGUAGE:CXX>` is a generator expression, specifically a conditional which checks whether `CXX` has been enabled previously (see [the docs](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:COMPILE_LANGUAGE)).

What makes you suggest it's incorrect?

**Comment by bkueng** [comment]
It checks for the language used for a given compilation unit, not whether a language is enabled.
It does not mention the case where a language is specified by the expression, but not enabled by the project (possibly because it seems like a logical expectation), so the behavior might depend on the cmake version.

**Comment by bkueng** [comment]
I can reproduce with cmake version 3.10.2, with this case:
```
project(test LANGUAGES C)

add_executable(test test.c)
target_compile_options(test PRIVATE -Wall
	-Wextra
	-Wshadow
	$<$<COMPILE_LANGUAGE:CXX>:-Wnon-virtual-dtor>
	)
```

```
CMake Error at CMakeLists.txt:4 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  $<COMPILE_LANGUAGE:...> Unknown language.
```
cmake version 3.22.2 does not produce an error.

**Comment by bkueng** [comment]
@pablogs9 do you have any reason not to remove `COMPILE_LANGUAGE:CXX`?

**Review by pablogs9 — APPROVED** [review]
LGTM since C++ related warnings does not apply to the C codebase of this project. Please @Acuadros95 take a look also.

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/78/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/73/)

**Comment by Acuadros95** [comment]
LGTM

**Review by Acuadros95 — APPROVED** [review]

**Pull request merged**
